const formulasWithIds1 = [
  { "id": "formula-101-1001", "formula": "f = f_0 \\cdot 2^{\\frac{n}{12}}", "name": "Frequency Scaling Formula", "title": "Frequency scaling in equal temperament tuning", "subtitle": "Used in music theory to calculate pitch changes", "ExplainitoryParagraph": "This formula is used in music theory to calculate the frequency of a note in equal temperament tuning, where each semitone is a fixed frequency ratio.", "DateofDiscovery": "", "AuthorName": "", "AuthorShortBio": "", "StepsToCalculate": "1. Identify the base frequency (f₀). 2. Calculate the number of semitones (n). 3. Apply the formula f = f₀ * 2^(n/12).", "unit": "Hz", "use_case": ["Music Theory", "Acoustics"], "related_formulas": [], "category": "Music Theory", "conditions_of_use": "Valid for equal temperament tuning systems", "difficulty_level": "Intermediate", "citation": "", "formula": "f = f_0 \\cdot 2^{\\frac{n}{12}}" },
  { "id": "formula-101-1002", "formula": "X_k = \\sum_{n=0}^{N-1} x_n \\cdot e^{-i \\frac{2\\pi}{N} k n}", "name": "Discrete Fourier Transform (DFT)", "title": "DFT for Frequency Components", "subtitle": "Fourier transform for extracting frequency components from a signal", "ExplainitoryParagraph": "This formula is the Discrete Fourier Transform (DFT), used for converting a time-domain signal into its frequency components.", "DateofDiscovery": "", "AuthorName": "", "AuthorShortBio": "", "StepsToCalculate": "1. Apply the DFT formula to the signal data. 2. Compute the sum for each frequency component. 3. Extract the resulting frequency components.", "unit": "Hz", "use_case": ["Signal Processing", "Acoustics"], "related_formulas": [], "category": "Advanced", "conditions_of_use": "Requires discrete-time data", "difficulty_level": "Advanced", "citation": "", "formula": "X_k = \\sum_{n=0}^{N-1} x_n \\cdot e^{-i \\frac{2\\pi}{N} k n}" }
];
const formulasWithIds2 = [
  { "id": "formula-101-1003", "formula": "C = A + B", "name": "Chord notation", "title": "Chord construction", "subtitle": "Simple addition of two notes", "ExplainitoryParagraph": "This formula represents the simple addition of two musical notes A and B to form a chord.", "DateofDiscovery": "", "AuthorName": "", "AuthorShortBio": "", "StepsToCalculate": "1. Identify the two notes (A and B). 2. Add the frequencies of A and B to form the chord.", "unit": "Hz", "use_case": ["Music Theory", "Harmony"], "related_formulas": [], "category": "Music Theory", "conditions_of_use": "Valid for two-note chord construction", "difficulty_level": "Beginner", "citation": "", "formula": "C = A + B" },
  { "id": "formula-101-1004", "formula": "A_4 = 440 \\text{ Hz}", "name": "Standard tuning for A4", "title": "Pitch standard for A4", "subtitle": "Reference frequency for musical tuning", "ExplainitoryParagraph": "This formula sets the pitch of A4 to 440 Hz, which is the standard tuning for the note A4 in music.", "DateofDiscovery": "", "AuthorName": "", "AuthorShortBio": "", "StepsToCalculate": "1. Set the A4 pitch to 440 Hz. 2. Tune other notes based on this reference frequency.", "unit": "Hz", "use_case": ["Music Tuning", "Acoustics"], "related_formulas": [], "category": "Music Tuning", "conditions_of_use": "Standard for musical instrument tuning", "difficulty_level": "Beginner", "citation": "", "formula": "A_4 = 440 \\text{ Hz}" },
  { "id": "formula-101-1005", "formula": "f_n = f_0 \\cdot 2^{n/12}", "name": "Frequency formula for the nth note", "title": "Frequency scaling for the nth note in equal temperament", "subtitle": "Calculate the frequency of any note in the scale", "ExplainitoryParagraph": "This formula calculates the frequency of the nth note based on the base frequency and equal temperament tuning.", "DateofDiscovery": "", "AuthorName": "", "AuthorShortBio": "", "StepsToCalculate": "1. Identify the base frequency (f₀). 2. Determine the number of semitones (n). 3. Apply the formula fₙ = f₀ * 2^(n/12).", "unit": "Hz", "use_case": ["Music Theory", "Acoustics"], "related_formulas": [], "category": "Music Theory", "conditions_of_use": "Valid for equal temperament tuning systems", "difficulty_level": "Intermediate", "citation": "", "formula": "f_n = f_0 \\cdot 2^{n/12}" }
];
const formulasWithIds3 = [
  { "id": "formula-101-1001", "formula": "f = f_0 \\cdot 2^{\\frac{n}{12}}", "name": "Frequency Scaling Formula", "title": "Frequency scaling in equal temperament tuning", "subtitle": "Used in music theory to calculate pitch changes", "ExplainitoryParagraph": "This formula is used in music theory to calculate the frequency of a note in equal temperament tuning, where each semitone is a fixed frequency ratio.", "DateofDiscovery": "", "AuthorName": "", "AuthorShortBio": "", "StepsToCalculate": "1. Identify the base frequency (f₀). 2. Calculate the number of semitones (n). 3. Apply the formula f = f₀ * 2^(n/12).", "unit": "Hz", "use_case": ["Music Theory", "Acoustics"], "related_formulas": [], "category": "Music Theory", "conditions_of_use": "Valid for equal temperament tuning systems", "difficulty_level": "Intermediate", "citation": "", "formula": "f = f_0 \\cdot 2^{\\frac{n}{12}}" },
  { "id": "formula-101-1002", "formula": "X_k = \\sum_{n=0}^{N-1} x_n \\cdot e^{-i \\frac{2\\pi}{N} k n}", "name": "Discrete Fourier Transform (DFT)", "title": "DFT for Frequency Components", "subtitle": "Fourier transform for extracting frequency components from a signal", "ExplainitoryParagraph": "This formula is the Discrete Fourier Transform (DFT), used for converting a time-domain signal into its frequency components.", "DateofDiscovery": "", "AuthorName": "", "AuthorShortBio": "", "StepsToCalculate": "1. Apply the DFT formula to the signal data. 2. Compute the sum for each frequency component. 3. Extract the resulting frequency components.", "unit": "Hz", "use_case": ["Signal Processing", "Acoustics"], "related_formulas": [], "category": "Advanced", "conditions_of_use": "Requires discrete-time data", "difficulty_level": "Advanced", "citation": "", "formula": "X_k = \\sum_{n=0}^{N-1} x_n \\cdot e^{-i \\frac{2\\pi}{N} k n}" }
];
const formulasWithIds4 = [
  { "id": "formula-101-1001", "formula": "f = f_0 \\cdot 2^{\\frac{n}{12}}", "name": "Frequency Scaling Formula", "title": "Frequency scaling in equal temperament tuning", "subtitle": "Used in music theory to calculate pitch changes", "ExplainitoryParagraph": "This formula is used in music theory to calculate the frequency of a note in equal temperament tuning, where each semitone is a fixed frequency ratio.", "DateofDiscovery": "", "AuthorName": "", "AuthorShortBio": "", "StepsToCalculate": "1. Identify the base frequency (f₀). 2. Calculate the number of semitones (n). 3. Apply the formula f = f₀ * 2^(n/12).", "unit": "Hz", "use_case": ["Music Theory", "Acoustics"], "related_formulas": [], "category": "Music Theory", "conditions_of_use": "Valid for equal temperament tuning systems", "difficulty_level": "Intermediate", "citation": "", "formula": "f = f_0 \\cdot 2^{\\frac{n}{12}}" },
];
const formulasWithIds5 = [
  { "id": "formula-101-1001", "formula": "f = f_0 \\cdot 2^{\\frac{n}{12}}", "name": "Frequency Scaling Formula", "title": "Frequency scaling in equal temperament tuning", "subtitle": "Used in music theory to calculate pitch changes", "ExplainitoryParagraph": "This formula is used in music theory to calculate the frequency of a note in equal temperament tuning, where each semitone is a fixed frequency ratio.", "DateofDiscovery": "Don't know", "AuthorName": "Michael Brown", "AuthorShortBio": "Michael Brown is a music theorist and acoustics expert.", "StepsToCalculate": "1. Identify the base frequency (f₀). 2. Calculate the number of semitones (n). 3. Apply the formula f = f₀ * 2^(n/12).", "unit": "Hz", "use_case": ["Music Theory", "Acoustics"], "related_formulas": [], "category": "Music Theory", "conditions_of_use": "Valid for equal temperament tuning systems", "difficulty_level": "Intermediate", "citation": "Don't know", "formula": "f = f_0 \\cdot 2^{\\frac{n}{12}}" }
];
const formulasWithIds6 = [
  { "id": "formula-101-1001", "formula": "f = f_0 \\cdot 2^{\\frac{n}{12}}", "name": "Frequency Scaling Formula", "title": "Frequency scaling in equal temperament tuning", "subtitle": "Used in music theory to calculate pitch changes", "ExplainitoryParagraph": "This formula is used in music theory to calculate the frequency of a note in equal temperament tuning, where each semitone is a fixed frequency ratio.", "DateofDiscovery": "", "AuthorName": "", "AuthorShortBio": "", "StepsToCalculate": "1. Identify the base frequency (f₀). 2. Calculate the number of semitones (n). 3. Apply the formula f = f₀ * 2^(n/12).", "unit": "Hz", "use_case": ["Music Theory", "Acoustics"], "related_formulas": [], "category": "Music Theory", "conditions_of_use": "Valid for equal temperament tuning systems", "difficulty_level": "Intermediate", "citation": "", "formula": "f = f_0 \\cdot 2^{\\frac{n}{12}}" },
  { "id": "formula-101-1002", "formula": "X_k = \\sum_{n=0}^{N-1} x_n \\cdot e^{-i \\frac{2\\pi}{N} k n}", "name": "Discrete Fourier Transform (DFT)", "title": "DFT for Frequency Components", "subtitle": "Fourier transform for extracting frequency components from a signal", "ExplainitoryParagraph": "This formula is the Discrete Fourier Transform (DFT), used for converting a time-domain signal into its frequency components.", "DateofDiscovery": "", "AuthorName": "", "AuthorShortBio": "", "StepsToCalculate": "1. Apply the DFT formula to the signal data. 2. Compute the sum for each frequency component. 3. Extract the resulting frequency components.", "unit": "Hz", "use_case": ["Signal Processing", "Acoustics"], "related_formulas": [], "category": "Advanced", "conditions_of_use": "Requires discrete-time data", "difficulty_level": "Advanced", "citation": "", "formula": "X_k = \\sum_{n=0}^{N-1} x_n \\cdot e^{-i \\frac{2\\pi}{N} k n}" }
];
const formulasWithIds7 = [
  { "id": "formula-101-1003", "formula": "C = A + B", "name": "Chord notation", "title": "Chord construction", "subtitle": "Simple addition of two notes", "ExplainitoryParagraph": "This formula represents the simple addition of two musical notes A and B to form a chord.", "DateofDiscovery": "", "AuthorName": "", "AuthorShortBio": "", "StepsToCalculate": "1. Identify the two notes (A and B). 2. Add the frequencies of A and B to form the chord.", "unit": "Hz", "use_case": ["Music Theory", "Harmony"], "related_formulas": [], "category": "Music Theory", "conditions_of_use": "Valid for two-note chord construction", "difficulty_level": "Beginner", "citation": "", "formula": "C = A + B" },
  { "id": "formula-101-1004", "formula": "A_4 = 440 \\text{ Hz}", "name": "Standard tuning for A4", "title": "Pitch standard for A4", "subtitle": "Reference frequency for musical tuning", "ExplainitoryParagraph": "This formula sets the pitch of A4 to 440 Hz, which is the standard tuning for the note A4 in music.", "DateofDiscovery": "", "AuthorName": "", "AuthorShortBio": "", "StepsToCalculate": "1. Set the A4 pitch to 440 Hz. 2. Tune other notes based on this reference frequency.", "unit": "Hz", "use_case": ["Music Tuning", "Acoustics"], "related_formulas": [], "category": "Music Tuning", "conditions_of_use": "Standard for musical instrument tuning", "difficulty_level": "Beginner", "citation": "", "formula": "A_4 = 440 \\text{ Hz}" },
  { "id": "formula-101-1005", "formula": "f_n = f_0 \\cdot 2^{n/12}", "name": "Frequency formula for the nth note", "title": "Frequency scaling for the nth note in equal temperament", "subtitle": "Calculate the frequency of any note in the scale", "ExplainitoryParagraph": "This formula calculates the frequency of the nth note based on the base frequency and equal temperament tuning.", "DateofDiscovery": "", "AuthorName": "", "AuthorShortBio": "", "StepsToCalculate": "1. Identify the base frequency (f₀). 2. Determine the number of semitones (n). 3. Apply the formula fₙ = f₀ * 2^(n/12).", "unit": "Hz", "use_case": ["Music Theory", "Acoustics"], "related_formulas": [], "category": "Music Theory", "conditions_of_use": "Valid for equal temperament tuning systems", "difficulty_level": "Intermediate", "citation": "", "formula": "f_n = f_0 \\cdot 2^{n/12}" }
];
